### ISSUE TITLE
老哥，有相关的报告或文章分享吗？

### ISSUE THREAD

**Issue by leungMr** [lcl124252/TSCFormer#1]
先生果然大义，将如此宝贵的代码公之于众，令人肃然起敬！小弟正在努力钻研您的代码，欲窥究竟，然愚钝之至，若有相关的报告或文档可供参阅，定能醍醐灌顶！若先生不吝赐教，小的感激不尽，祝您学术长虹，代码飞升！

**Comment by lcl124252** [comment]
> 先生果然大义，将如此宝贵的代码公之于众，令人肃然起敬！小弟正在努力钻研您的代码，欲窥究竟，然愚钝之至，若有相关的报告或文档可供参阅，定能醍醐灌顶！若先生不吝赐教，小的感激不尽，祝您学术长虹，代码飞升！

我们的论文还没发出来，暂时不能给你作为参考，你可以去arxiv搜索Semantic Scene Completion关键词自行查找论文观看
